print("welcome to offenso academy")
print("we have Offenso Certified Security Analyst ,Offenso Certified Security Professional , Certified junior hacker")
suggesion = input("which course would u like to choose ")
name = input("what is your name ")
print("hello, "+ name)
print ("congrates u selected "+ suggesion)
if suggesion == "Offenso Certified Security Analyst":
print("please enter the detales of the following")
email = input("Enter your email adresss ")
print("we have sent a conformation in your email=" + email)
phone = input("enter your phone number 91+ : ")
print("Phone number verfied")
location = input("please enter your location in kerala : ")
if suggesion == "Offenso Certified Security Professional":
print("please enter the detales of the following")
email = input("Enter your email adresss ")
print("we have sent a conformation in your email=" + email)
phone = input("enter your phone number 91+ : ")
print("Phone number verfied")
location = input("pleade")